services:
  docker_realtime_csharp:
    build:
      context: ./csharp_lp/App
      dockerfile: Dockerfile
    container_name: realtime_docker_csharp
    tty: true
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
        reservations:
          cpus: '1'
          memory: 10M