services:
  docker_realtime_csharp_fft:
    environment:
      TASK_TIME_PERIOD: 2
      TASK: "FFT"
      ITERATIONS: 100000
    build:
      context: ./csharp_lp/App
      dockerfile: Dockerfile
      args:
        args: foo
    container_name: realtime_docker_csharp_fft
    tty: true
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M
        reservations:
          cpus: '1'
          memory: 50M
  docker_realtime_csharp_lpo:
    environment:
      TASK_TIME_PERIOD: 2
      TASK: "LPO"
      ITERATIONS: 100000
    build:
      context: ./csharp_lp/App
      dockerfile: Dockerfile
      args:
        args: foo
    container_name: realtime_docker_csharp_lpo
    tty: true
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M
        reservations:
          cpus: '1'
          memory: 50M