services:
  producer:
    build: ./producer
    container_name: producer
    cap_add:
      - SYS_RAWIO
      - IPC_LOCK
    devices:
      - "/dev/mem:/dev/mem"
    cpuset: "2"
    command: ./producer
    environment:
      - REALTIME_KERNEL=1   

  consumer:
    build: ./consumer
    container_name: consumer
    cap_add:
      - SYS_RAWIO
      - IPC_LOCK
    devices:
      - "/dev/mem:/dev/mem"
    cpuset: "3"
    command: ./consumer
    environment:
      - REALTIME_KERNEL=1